### ISSUE TITLE
Unable to see the transaction name in New Relic

### ISSUE THREAD

**Issue by bionimic** [digiaonline/lumen-newrelic#17]
Hi, I have followed the guidelines to setup this into my project. Unfortunately I cant see it in my new relic. Do I have to setup anything other than what you have written in readme.md? 

Supposedly I can see the transaction name under transaction list right?

![Screen Shot 2020-03-03 at 3 52 38 PM](https://user-images.githubusercontent.com/9911699/75754103-0ed3d600-5d67-11ea-9948-2a66656a9973.png)

Or I mistakenly misunderstood the purpose of this package. Please help.
Thanks

**Comment by Jalle19** [comment]
What are you seeing instead of transaction names? The screenshot you posted clearly has named transactions.

**Comment by bionimic** [comment]
based on the text: "By default the transaction name will use the controller@action assigned to the route."

I thought I would see like ActorController@index something like that in the new relic

Do I need to add anything in the web.php? I am using version 1.1.0 due to my php version is 7.0 atm.

**Comment by Jalle19** [comment]
What do you see instead? /index.php?

**Comment by bionimic** [comment]
![Screen Shot 2020-03-04 at 6 46 35 AM](https://user-images.githubusercontent.com/9911699/75827138-f35ae080-5de3-11ea-9186-86a2d2c15d77.png)

![Screen Shot 2020-03-04 at 6 46 51 AM](https://user-images.githubusercontent.com/9911699/75827147-f950c180-5de3-11ea-93db-5d906fe6f7b9.png)

why do I see a lot of unknown transactions?

I dont even see the /index.php. where should I see that actually?

can you show some example in your new relic screen? thanks

**Comment by Jalle19** [comment]
You can mark the artisan transactions as background jobs (see the README). Unfortunately I can't show my New Relic dashboards, but for the most parts your transactions seem to be named already. The naming scheme can vary a bit depending on how you've configured your routes.

**Comment by bionimic** [comment]
It's ok. I can see it now in the detail section of the transaction. thank you for replying my messages!
