### ISSUE TITLE
Lumen 7.x and 8.x

### ISSUE THREAD

**Issue by ls-renaud-tilte** [digiaonline/lumen-newrelic#22]
### What did you do?

Tried to install the package with Lumen 7.x and 8.x

### What did you expect to happen?

Works as expected.

### What actually happened?

Conflicts in Composer packages, more specifically `illuminate/contracts`, required by `illuminate/support`.

### What versions of relevant language, framework and this module are you using?

Tried a `composer install` on the following `composer.json` files:

7.x
```
    "require": {
        "php": "^7.3",
        "laravel/lumen-framework": "^7.0",
        "nordsoftware/lumen-newrelic": "^2.0"
    },
```

8.x
```
    "require": {
        "php": "^7.3",
        "laravel/lumen-framework": "^8.0",
        "nordsoftware/lumen-newrelic": "^2.0"
    },
```

Works as expected with `"laravel/lumen-framework": "^6.0"`.

### Possible resolution

The following PRs are required (in that order) to fix the issue (tested with Lumen 7.x and 8.x).
- chained exception repo: https://github.com/digiaonline/lumen-chained-exception-handler/pull/9
- newrelic repo: https://github.com/digiaonline/lumen-newrelic/pull/23

**Comment by ls-renaud-tilte** [comment]
It may also require a bump / creation of a new version of the `nordsoftware/lumen-chained-exception-handler` to support higher version of illuminate contracts (`master` supports 7.x but stable releases are only accepting 6.x).

**Comment by Jalle19** [comment]
Tagged 3.0.0 (https://packagist.org/packages/nordsoftware/lumen-newrelic#3.0.0), thanks for your patience in getting this through! I keep reading the notifications but then I forget to take action.
