### ISSUE TITLE
config file is not loading

### ISSUE THREAD

**Issue by BigDaneLane** [digiaonline/lumen-newrelic#25]
### What did you do?
Upgraded to from 3.0.0 to 3.1.0
### What did you expect to happen?
It to keep working;)
### What actually happened?
config file is not loading.
3.1.0 was not working on my server because of case-sensitivity of file system: config/newRelic.php was not loading

### What versions of relevant language, framework and this module are you using?
nordsoftware/lumen-newrelic: "3.1.0"
laravel/lumen-framework: "8.1"
php: "7.3"

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

```
 config('newRelic.application_name'); // not working

 config('newrelic.application_name'); //working
```

**Comment by BigDaneLane** [comment]
PR with fix: https://github.com/digiaonline/lumen-newrelic/pull/24

**Comment by Jalle19** [comment]
Do you have a stack trace that illustrates the issue here? The configuration file is supposed to be optional, you don't have to add it unless you need to override any settings.

**Comment by BigDaneLane** [comment]
Im sorry, this is not the problem, I wil create another issue.
