### ISSUE TITLE
Customizing the render method

### ISSUE THREAD

**Issue by ibreakshit** [digiaonline/lumen-newrelic#3]
I can't seem to customize the report method from app>Exceptions>Handler.php like I should be able to. I suspect because all exceptions are being routed to the NewRelicExceptionHandler.php.

I need to modify the render method so that it returns json output instead of html output for http exceptions.

Is there a way around this without editing the NewRelicExceptionHandler.php file in the composer vendor package?

**Comment by ibreakshit** [comment]
Never mind, I just had to change

```php
$app->instance(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    new Nord\Lumen\ChainedExceptionHandler\ChainedExceptionHandler(
        new Laravel\Lumen\Exceptions\Handler(),
        [new Nord\Lumen\NewRelic\NewRelicExceptionHandler()]
    )
);
```

to the following

```php
$app->instance(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    new Nord\Lumen\ChainedExceptionHandler\ChainedExceptionHandler(
        new App\Exceptions\Handler(),
        [new Nord\Lumen\NewRelic\NewRelicExceptionHandler()]
    )
);
```

in my bootstrap>app.php

This should be in the documentation to avoid further confusion.

**Comment by hugovk** [comment]
@Hoya Please could you send a PR? Thanks!

**Comment by Jalle19** [comment]
Yeah I guess it could be clarified

**Comment by hugovk** [comment]
Closing, PRs still welcome to clarify docs.
