### ISSUE TITLE
Switch from develop to master?

### ISSUE THREAD

**Issue by hugovk** [digiaonline/lumen-newrelic#7]
Shall we standardise this repo with the others, and ditch the `develop` branch and set `master` as the main one?

If so:

* [x] Merge `develop` into `master`
* [x] Set `master` as default branch
      https://github.com/digiaonline/lumen-newrelic/settings/branches
* [x] Delete `develop`
      https://github.com/digiaonline/lumen-newrelic/branches

**Comment by Jalle19** [comment]
Sure

**Comment by Jalle19** [comment]
Done
